import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Playfair_Display } from "next/font/google";
import { type Metadata } from "next";
import { BreakpointIndicator } from "~/components/breakpoint-indicator";
import { Header } from "~/components/shared/header";
import Assistant from "~/components/shared/assistant";

import Footer from "~/components/shared/footer";

import { ToastProvider } from "~/components/ui/toast";
import { Toaster } from "sonner";
import { auth } from "~/server/auth";
import { db } from "~/server/db";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  const user = session?.user;

  let userdb = null;

  if (user) {
    userdb = await db.user.findUnique({
      where: {
        id: user?.id,
      },
    });
  }

  const points = userdb?.points;

  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${GeistSans.variable} ${playfair.variable} light`}
    >
      <body>
        <ToastProvider>
          <Header user={user} points={points} />
          <Assistant />
          {children}
          <BreakpointIndicator />
          <Toaster richColors />
          <Footer />
        </ToastProvider>
      </body>
    </html>
  );
}
